### ISSUE TITLE
Functionality in private plugin?

### ISSUE THREAD

**Issue by simonwimell** [luuptek/luuptek-wp-starter#38]
Hi! Your theme looks really interesting as a starter theme. But what functionality is in the private plugin, and why is it not public?

**Comment by luuptekman** [comment]
Hi, thanks for the interest.

Private mu-plugins partially reveals our default login user name and email address. Those are used to detect which user is currently logged in and then reveals buttons to notify customer about the changes in site.

Maybe I could remove that part from private plugin and make public for the rest..

**Comment by simonwimell** [comment]
Yeah, or if that function itself could be interesting for others, maybe just keep the user name/email in variables in a config file?

**Comment by luuptekman** [comment]
Free plugin is now available
https://github.com/luuptek/luuptek-starter-plugins

Take it a try :)

**Comment by simonwimell** [comment]
Awesome, thanks!
