### ISSUE TITLE
Setup problems

### ISSUE THREAD

**Issue by simonwimell** [luuptek/luuptek-wp-starter#41]
So I tried following the instructions. Cloning the theme, renaming folder, remove .git and run yarn. But then I got this:

```
$ sakke gulp configure-repository && npm run build
fatal: not a git repository (or any of the parent directories): .git
```

If i skip the .git removal it works. 

But then I get an issue when running `sakke watch`, returning `sakke: command not found`

Is that something I need to install?

**Comment by luuptekman** [comment]
Thanks for that! Yes there are indeed problems after I switche the whole thing on sakke.

Seems it needs some settings that are only on my local machine to work.

Need to revert back to default "yarn start / yarn prod"...

**Comment by luuptekman** [comment]
Build system is reverted back...Can you try now what happens?
- clone repo
- run `yarn` to install
- change `proxyUrl` in package.json to your local address
- Start developing by `yarn start` ==> open browser to `localhost:3000` ==> you should see your site and any changes to sass-files have immediate effect. Use `yarn prod` to build for production.

**Comment by luuptekman** [comment]
Closing as non active and setup most probably will work ok.
